language: go

go:
  - "1.10.x"
  - master

sudo: false
install:
    - go get -t

script: 
    - go build .
    - ./test/go-unit-tests.sh

after_success:
    - echo "Build Successful!"

after_failure:
    - echo "Build Failed!"
