language: go

go:
  - "1.12.x"

os: linux

env:
  - GO111MODULE=on

sudo: false
install:
    - go get -t

script: 
    - go build .
    - ./scripts/travis.sh

after_success:
    - echo "Build Successful!"

after_failure:
    - echo "Build Failed!"
